//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace i4myapps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_mwls
    {
        public int pk { get; set; }
        public string acc_no { get; set; }
        public string pat_id { get; set; }
        public string pat_name { get; set; }
        public string pat_sex { get; set; }
        public Nullable<System.DateTime> pat_dob { get; set; }
        public string referring_physician { get; set; }
        public string sr_description { get; set; }
        public string status { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> scheddate { get; set; }
    }
}
